Abstract subsystems from state machine
FRCTeam3255/2024_Offbot_Code pull request #136
Opened 2024-11-09 18:46 UTC by Alenguye582

my biggest regret in life is not making the LEDs blue and yellow for our team colors. it keeps me up at night

2024-11-09 18:51 UTC, ACat701 commented
I can't believe you've done this. The robot simply was not functional with teal and orange lights.

2024-11-11 16:17 UTC, TaylerUva requested changes

2024-11-11 16:17 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Autos/ShootSequence.java
> +            Commands.runOnce(() -> subStateMachine.setTargetState(TargetState.PREP_VISION)))
This line should be removed as it was from merge conflict.

2024-11-12 01:25 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Autos/ShootSequence.java
> +            Commands.runOnce(() -> subStateMachine.setTargetState(TargetState.PREP_VISION)))
```suggestion
```

2024-11-12 01:25 UTC, TaylerUva approved these changes

2024-11-12 01:27 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Autos/ShootSequence.java
> +                .tryState(RobotState.NONE)),
```suggestion
                .tryState(RobotState.NONE))
```

2024-11-12 02:16 UTC, ACat701 approved these changes
its beautiful

2024-11-12 02:16 UTC, merged