Mapped Buttons
FRCTeam3255/2024_Offbot_Code pull request #83
Opened 2024-09-29 20:18 UTC by Alenguye582

I had a little trouble with the game piece override; does that code seem like it should work?

2024-09-30 06:33 UTC, ACat701 requested changes, later dismissed
Can you also try to resolve #73 in this pr? I think they're similar enough where we can do them both now, and its basically the only other thing we need to program apart from the climb/trap

2024-09-30 06:33 UTC, ACat701 commented on src/main/java/frc/robot/subsystems/Transfer.java
> +    // return (constTransfer.NOTE_SENSOR_INVERT) ? !noteSensor.get() :
You can make this code a bit cleaner by moving the value of the note sensor into it's own line:

boolean noteSensorValue = (constTransfer.NOTE_SENSOR_INVERT) ? !noteSensor.get() : noteSensor.get();
return (noteSensorValue  || hasGamePiece);

2024-09-30 06:33 UTC, ACat701 commented on src/main/java/frc/robot/subsystems/Transfer.java
> +    // return (constTransfer.NOTE_SENSOR_INVERT) ? !noteSensor.get() :
I think the implementation of should work though!! We should test it before we merge it in

2024-09-30 06:34 UTC, ACat701 commented
I'll also see if i can find time to make a proper diagram and throw it in our readme :p

2024-09-30 14:32 UTC, TaylerUva commented
Btw this is one that we can test really well in sim

2024-10-05 01:23 UTC, TaylerUva commented
- [ ] Can't go from prep_vision to other prep_*
- [ ] DPad west is incorrect. It should be shuffle. Currently wing

FYI Note: can't do shoot in sim anymore (not issue for now)

2024-10-05 01:58 UTC, TaylerUva approved these changes

2024-10-05 01:58 UTC, merged